### PR TITLE
Fix RT.com URL detection, Add Slashdot and Techdirt icons 

### PR DESCRIPTION
**Pull request by GeniusMusings**

### CODE REVIEW

**Comment by rekado** [comment]
Thank you.  Could you rebase this onto the latest master please?

To update your own fork, add our repository as a remote, fetch commits from there, and rebase your commits on top of that:

    git remote add upstream https://github.com/Libertree/libertree-frontend-ramaze
    git fetch upstream
    git rebase upstream master

If you don't like to use Github for these things, you are also free to send me an email created by `git format-patch`.

**Comment by Pistos** [comment]
Something doesn't seem right.  Github says that 500+ files changed?  Perhaps a/the rebase was done incorrectly?  I'm busy till Jan 5 at the earliest, but I can try to tease apart your work and apply/rebase for you.

**Comment by rekado** [comment]
@GeniusMusings could you please try to rebase instead of merging?  You need to fetch the latest commits from upstream and then rebase your changes on top of that.  Then you can force push your changes.

**Comment by GeniusMusings** [comment]
Long story short, Git sucks. Read about it on LT later today.

**Comment by rekado** [comment]
You do not have to use git at all if you do not find it comfortable to use.  You can also just send us regular patches by getting the latest master code as a tarball, copying the file you want to modify, then modify the file, and then send us the diff via email: libertree@elephly.net

**Pull request closed without merging**
