### PR TITLE
add links to the index, add contributing

### PR DESCRIPTION
**Pull request by donnerkarlson**

### CODE REVIEW

**Comment by rekado** [comment]
Thank you for your contribution.

Two comments:

- the very first line in any of the documentation files should be the main heading.  The first heading is displayed with a nice Libertree logo to the left and is highlighted.  (See "Documentation index" here: https://oak.elephly.net/docs/show/en_GB/index).  Your new file does not have a heading.

- Could you please rebase your patches on top of latest master?  To do so please do the following from your local copy of your fork:

1. set up the official repo as a remote named "upstream": `git remote add upstream https://github.com/Libertree/libertree-frontend-ramaze`
2. fetch all commits from upstream: `git fetch upstream`
3. rebase your commits on top of upstream master: `git rebase upstream/master`

**Comment by donnerkarlson** [comment]
i did not forget the commit, but i have to istall git first, and i'm not really often on my pc at the moment..

**Comment by rekado** [comment]
That's fine.  Take your time!  Thanks for making the effort!

**Comment by Pistos** [comment]
Closing due to age and inactivity.  Create a new PR if desired.

**Pull request closed without merging**
